project:
  type: website
  output-dir: docs

website:
  favicon: assets/pydata-logo-final.png
  title: "PyData NYC"
  navbar:
    left:
      - href: index.qmd
        icon: house-heart
      - about.qmd
      - pages/social.qmd
      - href: https://numfocus.org/code-of-conduct
        text: Code of Conduct
    tools:
      - text: Meetup
        href: https://www.meetup.com/pydatanyc/
      - icon: linkedin
        href: https://www.linkedin.com/company/pydata-nyc/
      - icon: twitter-x
        href: https://twitter.com/pydatanyc
      - icon: discord
        href: https://discord.com/invite/XW9pzrtZJH

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



