project:
  type: website
  output-dir: docs

website:
  favicon: assets/pydata-logo-final.png
  title: "PyData NYC"
  sidebar:
    style: "docked"
    search: true
          
  navbar:
    left:
      - href: index.qmd
        icon: house-heart
      - href: pages/about.qmd
        text: About
      - href: pages/code_of_conduct.qmd
        text: Code of Conduct
      - href: pages/resources.qmd
        text: Resources
    tools:
      - icon: chat-fill
        href: https://www.meetup.com/pydatanyc/
        text: Meetup
      - icon: youtube
        href: https://www.youtube.com/@PyDataNYC
        text: YouTube 
      - icon: linkedin
        href: https://www.linkedin.com/company/pydata-nyc/
      - icon: twitter-x
        href: https://twitter.com/pydatanyc
      - icon: discord
        href: https://discord.gg/RxtaZvxYWM

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: article

execute:
  freeze: auto
  


